AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  DestinationBucketName:
    Type: String
    Description: Name of the existing destination S3 bucket
  SourceAccountId:
    Type: String
    Description: AWS Account ID where the source bucket exists
  ReplicationRoleArn:
    Type: String
    Description: ARN of the replication role from the source account
  DestinationKMSKeyArn:
    Type: String
    Description: KMS Key ARN for destination bucket in GovCloud

Resources:
  DestinationBucketVersioning:
    Type: AWS::S3::BucketVersioning
    Properties:
      Bucket: !Ref DestinationBucketName
      VersioningConfiguration:
        Status: Enabled

  DestinationBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DestinationBucketName
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: AllowReplication
          Effect: Allow
          Principal:
            AWS: !Ref ReplicationRoleArn
          Action:
          - s3:ReplicateObject
          - s3:ReplicateDelete
          - s3:ReplicateTags
          - s3:PutObject
          - s3:PutObjectVersionAcl
          - s3:PutObjectTagging
          - s3:GetObjectVersion
          - s3:GetObjectVersionAcl
          - s3:GetObjectVersionTagging
          - s3:ObjectOwnerOverrideToBucketOwner
          Resource:
          - !Sub 'arn:aws-us-gov:s3:::${DestinationBucketName}'
          - !Sub 'arn:aws-us-gov:s3:::${DestinationBucketName}/*'
        - Sid: AllowSourceAccountAccess
          Effect: Allow
          Principal:
            AWS: !Sub 'arn:aws-us-gov:iam::${SourceAccountId}:root'
          Action:
          - s3:List*
          - s3:Get*
          Resource:
          - !Sub 'arn:aws-us-gov:s3:::${DestinationBucketName}'
          - !Sub 'arn:aws-us-gov:s3:::${DestinationBucketName}/*'

  DestinationKMSKeyPolicy:
    Type: AWS::KMS::KeyPolicy
    Properties:
      KeyId: !Ref DestinationKMSKeyArn
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: AllowReplicationUseOfKey
          Effect: Allow
          Principal:
            AWS: !Ref ReplicationRoleArn
          Action:
          - kms:Encrypt
          - kms:GenerateDataKey
          Resource: '*'

Outputs:
  DestinationBucketName:
    Value: !Ref DestinationBucketName
    Description: Name of the destination bucket in GovCloud
