AWSTemplateFormatVersion: '2010-09-09'
Description: "IAM Role for Lambda function execution with comprehensive permissions for AWS GovCloud (US-West)"

Parameters:
  Environment:
    Type: String
    Description: "Environment name (e.g., dev, stage, prod)"
    Default: "dev"
    AllowedValues: [ "dev", "stage", "prod" ]

  RoleName:
    Type: String
    Description: "Name of the Lambda execution role"
    Default: "LambdaExecutionRole"

  S3BucketName:
    Type: String
    Description: "Name of the S3 bucket to grant access to"

  AWSRegion:
    Type: String
    Description: "AWS GovCloud Region"
    Default: "us-gov-west-1"
    AllowedValues: [ "us-gov-west-1" ]

Conditions:
  IsGovCloud: !Equals [ !Ref "AWS::Partition", "aws-us-gov" ]

Resources:
  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${Environment}-${RoleName}-govcloud"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Principal:
            Service:
            - "lambda.amazonaws.com"
            - "s3.amazonaws.com"
            - "apigateway.amazonaws.com"
            - "cloudtrail.amazonaws.com"
            - "kms.amazonaws.com"
            - "logs.amazonaws.com"
            - "cloudwatch.amazonaws.com"
          Action: "sts:AssumeRole"
      ManagedPolicyArns:
      - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
      Policies:
      - PolicyName: "CloudWatchEnhancedPolicy"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
            - "cloudwatch:PutMetricData"
            - "cloudwatch:GetMetricData"
            - "cloudwatch:ListMetrics"
            - "cloudwatch:GetMetricStatistics"
            - "cloudwatch:DescribeAlarms"
            Resource: "*"
          - Effect: "Allow"
            Action:
            - "logs:CreateLogGroup"
            - "logs:CreateLogStream"
            - "logs:PutLogEvents"
            - "logs:DescribeLogGroups"
            - "logs:DescribeLogStreams"
            Resource: !Sub "arn:${AWS::Partition}:logs:${AWSRegion}:${AWS::AccountId}:log-group:/aws/lambda/*"

      - PolicyName: "RDSAccessPolicy"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
            - "rds:DescribeDBInstances"
            - "rds:StartDBInstance"
            - "rds:StopDBInstance"
            - "rds:DescribeDBLogFiles"
            - "rds-db:connect"
            Resource: !Sub "arn:${AWS::Partition}:rds:${AWSRegion}:${AWS::AccountId}:db:*"
          - Effect: "Allow"
            Action:
            - "rds:ListTagsForResource"
            - "rds:DescribeDBSnapshots"
            Resource: "*"

      - PolicyName: "S3AccessPolicy"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
            - "s3:GetObject"
            - "s3:PutObject"
            - "s3:ListBucket"
            Resource:
            - !Sub "arn:${AWS::Partition}:s3:::${S3BucketName}"
            - !Sub "arn:${AWS::Partition}:s3:::${S3BucketName}/*"

      - PolicyName: "CloudTrailAccessPolicy"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
            - "cloudtrail:DescribeTrails"
            - "cloudtrail:GetTrailStatus"
            - "cloudtrail:LookupEvents"
            - "cloudtrail:ListTags"
            Resource: !Sub "arn:${AWS::Partition}:cloudtrail:${AWSRegion}:${AWS::AccountId}:trail/*"

      - PolicyName: "SecretManagerAccess"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
            - "secretsmanager:GetSecretValue"
            - "secretsmanager:DescribeSecret"
            Resource: !Sub "arn:${AWS::Partition}:secretsmanager:${AWSRegion}:${AWS::AccountId}:secret:*"

      - PolicyName: "KMSAccess"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
            - "kms:Decrypt"
            - "kms:GenerateDataKey"
            - "kms:Encrypt"
            Resource: !Sub "arn:${AWS::Partition}:kms:${AWSRegion}:${AWS::AccountId}:key/*"

      Tags:
      - Key: "Environment"
        Value: !Ref Environment
      - Key: "Name"
        Value: !Sub "${Environment}-${RoleName}-govcloud"
      - Key: "ManagedBy"
        Value: "CloudFormation"
      - Key: "LastUpdated"
        Value: !Ref "AWS::StackName"
      - Key: "Region"
        Value: !Ref AWSRegion
      - Key: "Classification"
        Value: "GovCloud"

Outputs:
  LambdaExecutionRoleArn:
    Description: "The ARN of the Lambda execution role"
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-GovCloud-LambdaRoleArn"

  LambdaExecutionRoleName:
    Description: "The name of the Lambda execution role"
    Value: !Ref LambdaExecutionRole
    Export:
      Name: !Sub "${AWS::StackName}-GovCloud-LambdaRoleName"
