AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Secrets Manager template for database credentials with
  enhanced security controls in GovCloud (US-West-1)'

Parameters:
  SecretName:
    Type: String
    Description: Name for the secret in Secrets Manager
    MinLength: 1
    MaxLength: 64
    AllowedPattern: '^[a-zA-Z0-9/_-]+$'
    ConstraintDescription: Secret name must contain only alphanumeric characters,
      underscores, hyphens, or slashes

  SecretDescription:
    Type: String
    Description: Description for the secret
    MinLength: 1
    MaxLength: 256

  Username:
    Type: String
    Description: Database username
    MinLength: 1
    MaxLength: 64
    ConstraintDescription: Username must be between 1 and 64 characters

  Password:
    Type: String
    NoEcho: true
    Description: Database password
    MinLength: 8
    MaxLength: 128
    ConstraintDescription: Password must be between 8 and 128 characters

  Engine:
    Type: String
    Description: Database engine type
    AllowedValues:
    - mysql
    - postgres
    - oracle
    - sqlserver
    Default: postgres

  Host:
    Type: String
    Description: Database host endpoint
    AllowedPattern: '^[a-zA-Z0-9.-]+$'
    ConstraintDescription: Host must contain only alphanumeric characters, dots, and hyphens

  Port:
    Type: Number
    Description: Database port number
    MinValue: 1024
    MaxValue: 65535
    Default: 5432
    ConstraintDescription: Port must be between 1024 and 65535

  DBName:
    Type: String
    Description: Database name
    MinLength: 1
    MaxLength: 64
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9_]*'
    ConstraintDescription: Database name must begin with a letter and contain only
      alphanumeric characters and underscores

  DBInstanceIdentifier:
    Type: String
    Description: Database instance identifier
    MinLength: 1
    MaxLength: 63
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9-]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric
      characters and hyphens

  KmsKeyId:
    Type: String
    Description: KMS key ID for encryption (ARN, ID, or alias)

  Environment:
    Type: String
    Description: Deployment environment
    AllowedValues:
    - dev
    - staging
    - prod
    Default: dev

Resources:
  DatabaseSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Ref SecretName
      Description: !Ref SecretDescription
      SecretString: !Sub |
        {
          "username": "${Username}",
          "password": "${Password}",
          "engine": "${Engine}",
          "host": "${Host}",
          "port": ${Port},
          "dbname": "${DBName}",
          "dbInstanceIdentifier": "${DBInstanceIdentifier}",
          "credentials": "IAM"
        }
      KmsKeyId: !Ref KmsKeyId
      Tags:
      - Key: Environment
        Value: !Ref Environment
      - Key: Application
        Value: Database
      - Key: ManagedBy
        Value: CloudFormation
      - Key: SecretName
        Value: !Ref SecretName
      - Key: SecretDescription
        Value: !Ref SecretDescription

  DatabaseSecretResourcePolicy:
    Type: 'AWS::SecretsManager::ResourcePolicy'
    Properties:
      SecretId: !Ref DatabaseSecret
      ResourcePolicy:
        Version: '2012-10-17'
        Statement:
        - Sid: EnableSecretAccess
          Effect: Allow
          Principal:
            AWS: !Sub 'arn:aws-us-gov:iam::${AWS::AccountId}:root'
          Action:
          - secretsmanager:GetSecretValue
          - secretsmanager:DescribeSecret
          Resource: !Ref DatabaseSecret
          Condition:
            StringEquals:
              aws:PrincipalAccount: !Ref 'AWS::AccountId'
            StringLike:
              'secretsmanager:ResourceTag/Environment': !Ref Environment

Outputs:
  SecretArn:
    Description: ARN of the created secret
    Value: !Ref DatabaseSecret
    Export:
      Name: !Sub '${AWS::StackName}-SecretArn'

  SecretNameOutput:
    Description: Name of the created secret
    Value: !Ref SecretName
    Export:
      Name: !Sub '${AWS::StackName}-SecretName'
