AWSTemplateFormatVersion: '2010-09-09'
Description: "IAM Role for API Gateway execution in AWS GovCloud (US-West)"

Parameters:
  Environment:
    Type: String
    Description: "Environment name (e.g., dev, stage, prod)"
    Default: "dev"
    AllowedValues: [ "dev", "stage", "prod" ]

  RoleName:
    Type: String
    Description: "Name of the API execution role"
    Default: "APIExecutionRole"

  S3BucketName:
    Type: String
    Description: "Name of the S3 bucket to grant access to"

  AWSRegion:
    Type: String
    Description: "AWS GovCloud Region"
    Default: "us-gov-west-1"
    AllowedValues: [ "us-gov-west-1" ]

Conditions:
  IsGovCloud: !Equals [ !Ref "AWS::Partition", "aws-us-gov" ]

Resources:
  APIExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${Environment}-${RoleName}-govcloud"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Principal:
            Service:
            - "apigateway.amazonaws.com"
            - "lambda.amazonaws.com"
            - "s3.amazonaws.com"
          Action: "sts:AssumeRole"
      ManagedPolicyArns:
      - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"
      Policies:
      - PolicyName: "CloudWatchEnhancedPolicy"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
            - "cloudwatch:PutMetricData"
            - "cloudwatch:GetMetricData"
            - "cloudwatch:ListMetrics"
            - "cloudwatch:GetMetricStatistics"
            - "cloudwatch:DescribeAlarms"
            Resource: "*"
          - Effect: "Allow"
            Action:
            - "logs:CreateLogGroup"
            - "logs:CreateLogStream"
            - "logs:PutLogEvents"
            - "logs:DescribeLogGroups"
            - "logs:DescribeLogStreams"
            Resource:
            - !Sub "arn:${AWS::Partition}:logs:${AWSRegion}:${AWS::AccountId}:log-group:/aws/lambda/*"
            - !Sub "arn:${AWS::Partition}:logs:${AWSRegion}:${AWS::AccountId}:log-group:/aws/apigateway/*"

      - PolicyName: "S3AccessPolicy"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
            - "s3:GetObject"
            - "s3:PutObject"
            - "s3:DeleteObject"
            - "s3:GetObjectVersion"
            - "s3:GetObjectACL"
            - "s3:PutObjectACL"
            - "s3:ListBucket"
            Resource:
            - !Sub "arn:${AWS::Partition}:s3:::${S3BucketName}"
            - !Sub "arn:${AWS::Partition}:s3:::${S3BucketName}/*"

      - PolicyName: "KMSAccess"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
            - "kms:Decrypt"
            - "kms:GenerateDataKey"
            - "kms:Encrypt"
            Resource: !Sub "arn:${AWS::Partition}:kms:${AWSRegion}:${AWS::AccountId}:key/*"

      Tags:
      - Key: "Environment"
        Value: !Ref Environment
      - Key: "Name"
        Value: !Sub "${Environment}-${RoleName}-govcloud"
      - Key: "ManagedBy"
        Value: "CloudFormation"
      - Key: "LastUpdated"
        Value: !Ref "AWS::StackName"
      - Key: "Region"
        Value: !Ref AWSRegion
      - Key: "Classification"
        Value: "GovCloud"
      - Key: "Service"
        Value: "API Gateway"

Outputs:
  APIExecutionRoleArn:
    Description: "The ARN of the API execution role"
    Value: !GetAtt APIExecutionRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-GovCloud-APIRoleArn"

  APIExecutionRoleName:
    Description: "The name of the API execution role"
    Value: !Ref APIExecutionRole
    Export:
      Name: !Sub "${AWS::StackName}-GovCloud-APIRoleName"
